apiVersion: v1
kind: Service
metadata:
  name: inventario-products-service
spec:
  selector:
    app: inventario-products
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer
